application:
  max-allowed-books: 2

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: krisbaz
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/mydb
#    username: root
#    password: 12345678
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true